title: "Vector.js"
blurb: Vector is an open source javascript library for creating interactive scalable vector graphics.
baseURL: "https://vectorjs.org"
languageCode: "en-us"
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsUseClasses: true
publishDir: "../docs/"
staticDir:
  - static
  - ../api/
  - ../css/
  - ../dist/
  - ../resources/

params:
  repositoryURL: "https://github.com/vector-js/vector.git"
